CREATE OR REPLACE PROCEDURE PR_SAVE_ENDEKS_FIYAT(
    p_endekskodu IN VARCHAR2,
    p_tarih IN DATE,
    p_fiyat IN NUMBER
) AS
BEGIN
    MERGE INTO TB_ENDEKS_FIYAT e
    USING (SELECT p_endekskodu AS ENDEKS_KODU, p_tarih AS TARIH, p_fiyat AS FIYAT FROM DUAL) src
    ON (e.ENDEKS_KODU = src.ENDEKS_KODU AND e.TARIH = src.TARIH)
    WHEN MATCHED THEN
        UPDATE SET e.FIYAT = src.FIYAT
    WHEN NOT MATCHED THEN
        INSERT (ENDEKS_KODU, TARIH, FIYAT)
        VALUES (src.ENDEKS_KODU, src.TARIH, src.FIYAT);
END;
/
