-- 1. TB_FONLAR Tablosu: Sistemdeki fonların (örneğin AFT, YAY) temel bilgilerini tutar.
CREATE TABLE TB_FONLAR (
    FON_KODU VARCHAR2(10) PRIMARY KEY,
    FON_ADI VARCHAR2(255) NOT NULL,
    FON_KATEGORI VARCHAR2(50),
    FON_TURU VARCHAR2(100),
    KURUCU VARCHAR2(255),
    DURUM VARCHAR2(30) DEFAULT 'AKTIF'
);

-- 2. TB_IS_GUNU Tablosu: Resmi tatilleri vb. ayırt etmek için takvim günlerini tutar.
CREATE TABLE TB_IS_GUNU (
    TARIH DATE PRIMARY KEY,
    IS_GUNU_MU NUMBER(1) DEFAULT 1,
    ACIKLAMA VARCHAR2(100)
);

-- 3. TB_FON_FIYAT Tablosu: Fonların her günkü fiyat bilgilerini tutar.
CREATE TABLE TB_FON_FIYAT (
    FON_KODU VARCHAR2(10),
    TARIH DATE,
    BIRIM_FIYAT NUMBER(20, 6),
    CONSTRAINT PK_FON_FIYAT PRIMARY KEY (FON_KODU, TARIH),
    CONSTRAINT FK_FON_FIYAT_FON FOREIGN KEY (FON_KODU) REFERENCES TB_FONLAR(FON_KODU)
);

-- 4. TB_ENDEKS_FIYAT Tablosu: BIST100 gibi gösterge endekslerin günlük fiyatları.
CREATE TABLE TB_ENDEKS_FIYAT (
    ENDEKS_KODU VARCHAR2(50),
    TARIH DATE,
    FIYAT NUMBER(20, 6),
    CONSTRAINT PK_ENDEKS_FIYAT PRIMARY KEY (ENDEKS_KODU, TARIH)
);

-- 5. TB_RISK_SONUC Tablosu: Hesaplayacağımız analiz sonuçlarını kaydedeceğimiz yer.
CREATE TABLE TB_RISK_SONUC (
    FON_KODU VARCHAR2(10),
    HESAPLAMA_TARIHI DATE,
    BETA NUMBER(15, 6),
    ALPHA NUMBER(15, 6),
    SHARPE NUMBER(15, 6),
    SORTINO NUMBER(15, 6),
    TREYNOR NUMBER(15, 6),
    VOLATILITE NUMBER(15, 6),
    VAR_RMD NUMBER(15, 6),
    DOWNSIDE_RISK NUMBER(15, 6),
    DEGISIM_KATSAYISI NUMBER(15, 6),
    GUNLUK_GETIRI NUMBER(15, 6),
    YILLIK_GETIRI NUMBER(15, 6),
    CONSTRAINT PK_RISK_SONUC PRIMARY KEY (FON_KODU, HESAPLAMA_TARIHI),
    CONSTRAINT FK_RISK_SONUC_FON FOREIGN KEY (FON_KODU) REFERENCES TB_FONLAR(FON_KODU)
);

-- 6. TB_HESAPLAMA_LOG Tablosu: Log tutacağımız günlük.
CREATE TABLE TB_HESAPLAMA_LOG (
    LOG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FON_KODU VARCHAR2(10),
    ISLEM_TARIHI TIMESTAMP DEFAULT SYSTIMESTAMP,
    DURUM VARCHAR2(20),
    HATA_MESAJI VARCHAR2(4000),
    SURE_MS NUMBER
);

-- 7. TB_SISTEM_PARAMETRE Tablosu: Risksiz getiri oranı vb. sistem genelinde kullanılan parametreler.
CREATE TABLE TB_SISTEM_PARAMETRE (
    PARAMETRE_ADI VARCHAR2(100) PRIMARY KEY,
    DEGER NUMBER(15, 6) NOT NULL,
    ACIKLAMA VARCHAR2(500)
);
