-- TB_FONLAR TABLOSU KURUCU VE KATEGORİ OTOMATİK GÜNCELLEME KOMUTLARI
-- Bu script, TEFAS'tan fon verileri (CSV upload) yüklendikten sonra çalıştırılarak
-- fonların resmi kurucu adlarını ve fon kategorilerini otomatik olarak doldurur.

-- FON KATEGORİSİ GÜNCELLEMELERİ

-- Borsa Yatırım Fonları (BYF)
UPDATE TB_FONLAR 
SET FON_KATEGORI = 'BORSA_FONU' 
WHERE UPPER(FON_ADI) LIKE '%BORSA%';
COMMIT;

-- Emeklilik Yatırım Fonları (EYF)
UPDATE TB_FONLAR 
SET FON_KATEGORI = 'EMEKLILIK_FONU' 
WHERE UPPER(FON_ADI) LIKE '%EMEKLİLİK%' 
   OR UPPER(FON_ADI) LIKE '%EMEKLILIK%' 
   OR UPPER(FON_ADI) LIKE '%EYF%';
COMMIT;

-- Menkul Kıymet Yatırım Fonları
UPDATE TB_FONLAR 
SET FON_KATEGORI = 'YATIRIM_FONU' 
WHERE UPPER(FON_ADI) LIKE '%SERBEST ÖZEL FON%' 
   OR FON_KATEGORI IS NULL;
COMMIT;


-- KURUCU ÜNVAN GÜNCELLEMELERİ (MENKUL VE BORSA FONLARI)

UPDATE TB_FONLAR SET KURUCU = 'A1 CAPİTAL PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%A1 CAPİTAL%' OR UPPER(FON_ADI) LIKE '%A1 CAPITAL%';
UPDATE TB_FONLAR SET KURUCU = 'AHLATCI PORTFÖY YÖNETİMİ ANONİM ŞİRKETİ' WHERE UPPER(FON_ADI) LIKE '%AHLATCI%';
UPDATE TB_FONLAR SET KURUCU = 'AK PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%AK PORTFÖY%' OR UPPER(FON_ADI) LIKE '%AK PORTFOY%';
UPDATE TB_FONLAR SET KURUCU = 'AKTİF PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%AKTİF PORTFÖY%' OR UPPER(FON_ADI) LIKE '%AKTIF PORTFOY%';
UPDATE TB_FONLAR SET KURUCU = 'ALBARAKA PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%ALBARAKA%';
UPDATE TB_FONLAR SET KURUCU = 'ALLBATROSS PORTFÖY YÖNETİMİ ANONİM ŞİRKETİ' WHERE UPPER(FON_ADI) LIKE '%ALLBATROSS%';
UPDATE TB_FONLAR SET KURUCU = 'ASTRA PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%ASTRA%';
UPDATE TB_FONLAR SET KURUCU = 'ATA PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%ATA PORTFÖY%' OR UPPER(FON_ADI) LIKE '%ATA PORTFOY%';
UPDATE TB_FONLAR SET KURUCU = 'ATLAS PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%ATLAS%';
UPDATE TB_FONLAR SET KURUCU = 'AURA PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%AURA%';
UPDATE TB_FONLAR SET KURUCU = 'AZİMUT PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%AZİMUT%' OR UPPER(FON_ADI) LIKE '%AZIMUT%';

UPDATE TB_FONLAR SET KURUCU = 'BULLS PORTFÖY YÖNETİMİ ANONİM ŞİRKETİ' WHERE UPPER(FON_ADI) LIKE '%BULLS%';
UPDATE TB_FONLAR SET KURUCU = 'BV PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%BV PORTFÖY%' OR UPPER(FON_ADI) LIKE '%BV PORTFOY%';
UPDATE TB_FONLAR SET KURUCU = 'DENİZ PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%DENİZ PORTFÖY%' OR UPPER(FON_ADI) LIKE '%DENIZ PORTFOY%';

UPDATE TB_FONLAR SET KURUCU = 'EMAA BLUE PORTFÖY YÖNETİMİ ANONİM ŞİRKETİ' WHERE UPPER(FON_ADI) LIKE '%EMAA%';
UPDATE TB_FONLAR SET KURUCU = 'EMLAK KATILIM PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%EMLAK KATILIM%';
UPDATE TB_FONLAR SET KURUCU = 'FİBA PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%FİBA%' OR UPPER(FON_ADI) LIKE '%FIBA%';
UPDATE TB_FONLAR SET KURUCU = 'FONMAP PORTFÖY YÖNETİMİ ANONİM ŞİRKETİ' WHERE UPPER(FON_ADI) LIKE '%FONMAP%';

UPDATE TB_FONLAR SET KURUCU = 'GARANTİ PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%GARANTİ PORTFÖY%' OR UPPER(FON_ADI) LIKE '%GARANTI PORTFOY%';
UPDATE TB_FONLAR SET KURUCU = 'GEDİK PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%GEDİK%' OR UPPER(FON_ADI) LIKE '%GEDIK%';
UPDATE TB_FONLAR SET KURUCU = 'GLOBAL MD PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%GLOBAL MD%' OR UPPER(FON_ADI) LIKE '%GLOBAL PORTFÖY%';
UPDATE TB_FONLAR SET KURUCU = 'GOLDEN GLOBAL PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%GOLDEN GLOBAL%';
UPDATE TB_FONLAR SET KURUCU = 'HAS PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%HAS PORTFÖY%' OR UPPER(FON_ADI) LIKE '%HAS PORTFOY%';
UPDATE TB_FONLAR SET KURUCU = 'HEDEF PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%HEDEF%';
UPDATE TB_FONLAR SET KURUCU = 'HSBC PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%HSBC%';

UPDATE TB_FONLAR SET KURUCU = 'ICBC TURKEY PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%ICBC%';
UPDATE TB_FONLAR SET KURUCU = 'INVEO PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%INVEO%';
UPDATE TB_FONLAR SET KURUCU = 'İNCİR PORTFÖY YÖNETİMİ ANONİM ŞİRKETİ' WHERE UPPER(FON_ADI) LIKE '%İNCİR%' OR UPPER(FON_ADI) LIKE '%INCIR%';
UPDATE TB_FONLAR SET KURUCU = 'İSTANBUL PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%İSTANBUL PORTFÖY%' OR UPPER(FON_ADI) LIKE '%ISTANBUL PORTFOY%';
UPDATE TB_FONLAR SET KURUCU = 'İŞ PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%İŞ PORTFÖY%' OR UPPER(FON_ADI) LIKE '%IS PORTFOY%';

UPDATE TB_FONLAR SET KURUCU = 'KARE PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%KARE PORTFÖY%' OR UPPER(FON_ADI) LIKE '%KARE PORTFOY%';
UPDATE TB_FONLAR SET KURUCU = 'KUVEYT TÜRK PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%KUVEYT TÜRK%' OR UPPER(FON_ADI) LIKE '%KUVEYTTÜRK%';
UPDATE TB_FONLAR SET KURUCU = 'LOGOS PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%LOGOS%';
UPDATE TB_FONLAR SET KURUCU = 'MARMARA CAPİTAL PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%MARMARA%';
UPDATE TB_FONLAR SET KURUCU = 'MEKSA PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%MEKSA%';
UPDATE TB_FONLAR SET KURUCU = 'MT PORTFÖY YÖNETİMİ ANONİM ŞİRKETİ' WHERE UPPER(FON_ADI) LIKE '%MT PORTFÖY%' OR UPPER(FON_ADI) LIKE '%MT PORTFOY%';

UPDATE TB_FONLAR SET KURUCU = 'NEO PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%NEO PORTFÖY%' OR UPPER(FON_ADI) LIKE '%NEO PORTFOY%';
UPDATE TB_FONLAR SET KURUCU = 'NUROL PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%NUROL%';
UPDATE TB_FONLAR SET KURUCU = 'ONE PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%ONE PORTFÖY%' OR UPPER(FON_ADI) LIKE '%ONE PORTFOY%';
UPDATE TB_FONLAR SET KURUCU = 'OSMANLI PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%OSMANLI%';
UPDATE TB_FONLAR SET KURUCU = 'OYAK PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%OYAK%';
UPDATE TB_FONLAR SET KURUCU = 'PARDUS PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%PARDUS%';
UPDATE TB_FONLAR SET KURUCU = 'PERFORM PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%PERFORM%';
UPDATE TB_FONLAR SET KURUCU = 'PHİLLİP PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%PHİLLİP%' OR UPPER(FON_ADI) LIKE '%PHILLIP%';
UPDATE TB_FONLAR SET KURUCU = 'PİRAMİT PORTFÖY YÖNETİMİ ANONİM ŞİRKETİ' WHERE UPPER(FON_ADI) LIKE '%PİRAMİT%' OR UPPER(FON_ADI) LIKE '%PIRAMIT%';
UPDATE TB_FONLAR SET KURUCU = 'PUSULA PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%PUSULA%';

UPDATE TB_FONLAR SET KURUCU = 'QNB PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%QNB%' OR UPPER(FON_ADI) LIKE '%FİNANS PORTFÖY%';
UPDATE TB_FONLAR SET KURUCU = 'RE-PİE PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%RE-PİE%' OR UPPER(FON_ADI) LIKE '%RE-PIE%' OR UPPER(FON_ADI) LIKE '%REPIE%';
UPDATE TB_FONLAR SET KURUCU = 'ROTA PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%ROTA%';

UPDATE TB_FONLAR SET KURUCU = 'SPARTA PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%SPARTA%';
UPDATE TB_FONLAR SET KURUCU = 'STATECH PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%STATECH%';
UPDATE TB_FONLAR SET KURUCU = 'STRATEJİ PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%STRATEJİ%' OR UPPER(FON_ADI) LIKE '%STRATEJI%';

UPDATE TB_FONLAR SET KURUCU = 'TACİRLER PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%TACİRLER%';
UPDATE TB_FONLAR SET KURUCU = 'TEB PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%TEB PORTFÖY%';
UPDATE TB_FONLAR SET KURUCU = 'TERA PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%TERA%';
UPDATE TB_FONLAR SET KURUCU = 'TRİVE PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%TRİVE%' OR UPPER(FON_ADI) LIKE '%TRIVE%';
UPDATE TB_FONLAR SET KURUCU = 'ÜNLÜ PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%ÜNLÜ%' OR UPPER(FON_ADI) LIKE '%UNLU%';

UPDATE TB_FONLAR SET KURUCU = 'V PORTFÖY YÖNETİMİ ANONİM ŞİRKETİ' WHERE UPPER(FON_ADI) LIKE '%V PORTFÖY%' OR UPPER(FON_ADI) LIKE '%V PORTFOY%';
UPDATE TB_FONLAR SET KURUCU = 'VAKIF KATILIM PORTFÖY YÖNETİMİ ANONİM ŞİRKETİ' WHERE UPPER(FON_ADI) LIKE '%VAKIF KATILIM%';
UPDATE TB_FONLAR SET KURUCU = 'VAKIF PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%VAKIF PORTFÖY%' OR UPPER(FON_ADI) LIKE '%VAKIF PORTFOY%';
UPDATE TB_FONLAR SET KURUCU = 'VEGA PORTFÖY YÖNETİMİ ANONİM ŞİRKETİ' WHERE UPPER(FON_ADI) LIKE '%VEGA%';
UPDATE TB_FONLAR SET KURUCU = 'YAPI KREDİ PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%YAPI KREDİ%' OR UPPER(FON_ADI) LIKE '%YAPI KREDI%';
UPDATE TB_FONLAR SET KURUCU = 'ZİRAAT PORTFÖY YÖNETİMİ A.Ş.' WHERE UPPER(FON_ADI) LIKE '%ZİRAAT PORTFÖY%' OR UPPER(FON_ADI) LIKE '%ZIRAAT PORTFOY%';

-- EMEKLİLİK FONLARINA ÖZEL KURUCU ÜNVAN GÜNCELLEMELERİ
UPDATE TB_FONLAR SET KURUCU = 'AGESA HAYAT VE EMEKLİLİK A.Ş.' WHERE FON_KATEGORI = 'EMEKLILIK_FONU' AND (UPPER(FON_ADI) LIKE '%AGESA%' OR UPPER(FON_ADI) LIKE '%AVİSA%' OR UPPER(FON_ADI) LIKE '%AVISA%');
UPDATE TB_FONLAR SET KURUCU = 'ALLİANZ YAŞAM VE EMEKLİLİK A.Ş.' WHERE FON_KATEGORI = 'EMEKLILIK_FONU' AND (UPPER(FON_ADI) LIKE '%ALLİANZ YAŞAM%' OR UPPER(FON_ADI) LIKE '%ALLIANZ YASAM%');
UPDATE TB_FONLAR SET KURUCU = 'ALLİANZ HAYAT VE EMEKLİLİK A.Ş.' WHERE FON_KATEGORI = 'EMEKLILIK_FONU' AND (UPPER(FON_ADI) LIKE '%ALLİANZ%' OR UPPER(FON_ADI) LIKE '%ALLIANZ%') AND (KURUCU IS NULL OR KURUCU LIKE '%PORTFÖY%');
UPDATE TB_FONLAR SET KURUCU = 'ANADOLU HAYAT EMEKLİLİK A.Ş.' WHERE FON_KATEGORI = 'EMEKLILIK_FONU' AND (UPPER(FON_ADI) LIKE '%ANADOLU HAYAT%' OR UPPER(FON_ADI) LIKE '%ANADOLU EMEKLİLİK%' OR UPPER(FON_ADI) LIKE '%AHE%');
UPDATE TB_FONLAR SET KURUCU = 'AXA HAYAT VE EMEKLİLİK A.Ş.' WHERE FON_KATEGORI = 'EMEKLILIK_FONU' AND UPPER(FON_ADI) LIKE '%AXA%';
UPDATE TB_FONLAR SET KURUCU = 'BEREKET EMEKLİLİK VE HAYAT A.Ş.' WHERE FON_KATEGORI = 'EMEKLILIK_FONU' AND UPPER(FON_ADI) LIKE '%BEREKET%';
UPDATE TB_FONLAR SET KURUCU = 'BNP PARİBAS CARDİF EMEKLİLİK A.Ş.' WHERE FON_KATEGORI = 'EMEKLILIK_FONU' AND (UPPER(FON_ADI) LIKE '%BNP%' OR UPPER(FON_ADI) LIKE '%CARDİF%' OR UPPER(FON_ADI) LIKE '%CARDIF%');
UPDATE TB_FONLAR SET KURUCU = 'GARANTİ EMEKLİLİK VE HAYAT A.Ş.' WHERE FON_KATEGORI = 'EMEKLILIK_FONU' AND (UPPER(FON_ADI) LIKE '%GARANTİ%' OR UPPER(FON_ADI) LIKE '%GARANTI%');
UPDATE TB_FONLAR SET KURUCU = 'HDİ FİBA EMEKLİLİK VE HAYAT A.Ş.' WHERE FON_KATEGORI = 'EMEKLILIK_FONU' AND (UPPER(FON_ADI) LIKE '%HDİ%' OR UPPER(FON_ADI) LIKE '%FİBA%' OR UPPER(FON_ADI) LIKE '%HDI%');
UPDATE TB_FONLAR SET KURUCU = 'KATILIM EMEKLİLİK VE HAYAT A.Ş.' WHERE FON_KATEGORI = 'EMEKLILIK_FONU' AND (UPPER(FON_ADI) LIKE '%KATILIM EMEKLİLİK%' OR UPPER(FON_ADI) LIKE '%KATILIM EMEKLILIK%');
UPDATE TB_FONLAR SET KURUCU = 'METLİFE EMEKLİLİK VE HAYAT A.Ş.' WHERE FON_KATEGORI = 'EMEKLILIK_FONU' AND (UPPER(FON_ADI) LIKE '%METLİFE%' OR UPPER(FON_ADI) LIKE '%METLIFE%');
UPDATE TB_FONLAR SET KURUCU = 'QNB SAĞLIK HAYAT SİGORTA VE EMEKLİLİK A.Ş.' WHERE FON_KATEGORI = 'EMEKLILIK_FONU' AND (UPPER(FON_ADI) LIKE '%QNB%' OR UPPER(FON_ADI) LIKE '%CİGNA%' OR UPPER(FON_ADI) LIKE '%CIGNA%');
UPDATE TB_FONLAR SET KURUCU = 'TÜRKİYE HAYAT VE EMEKLİLİK A.Ş.' WHERE FON_KATEGORI = 'EMEKLILIK_FONU' AND (UPPER(FON_ADI) LIKE '%TÜRKİYE%' OR UPPER(FON_ADI) LIKE '%TURKIYE%');
UPDATE TB_FONLAR SET KURUCU = 'VİENNALİFE EMEKLİLİK VE HAYAT A.Ş.' WHERE FON_KATEGORI = 'EMEKLILIK_FONU' AND (UPPER(FON_ADI) LIKE '%VİENNALİFE%' OR UPPER(FON_ADI) LIKE '%VIENNALIFE%' OR UPPER(FON_ADI) LIKE '%AEGON%');
UPDATE TB_FONLAR SET KURUCU = 'ZURİCH YAŞAM VE EMEKLİLİK A.Ş.' WHERE FON_KATEGORI = 'EMEKLILIK_FONU' AND (UPPER(FON_ADI) LIKE '%ZURİCH%' OR UPPER(FON_ADI) LIKE '%ZURICH%');

COMMIT;
