server.port=8080

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREE
spring.datasource.username=RISKANALIZ
spring.datasource.password=12345
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

logging.level.org.springframework.jdbc=DEBUG
