-- Fiyat tablolarında tarih bazlı aramalar çok sık olacağı için:
CREATE INDEX IDX_FON_FIYAT_TARIH ON TB_FON_FIYAT(TARIH);
CREATE INDEX IDX_ENDEKS_FIYAT_TARIH ON TB_ENDEKS_FIYAT(TARIH);
CREATE INDEX IDX_RISK_SONUC_FON ON TB_RISK_SONUC(FON_KODU, HESAPLAMA_TARIHI);
